### ISSUE TITLE
About ground truth of fine reg

### ISSUE THREAD

**Issue by luminous0809** [GAP-LAB-CUHK-SZ/GaussReg#13]
How can I get the ground-truth depth of p in sets of valid points？Does we use ground truth depth map ？How can we get them？

**Comment by Jiahao620** [comment]
We use ground-truth depth maps in original ScanNet dataset. You can download its RGB-D sequence in https://github.com/ScanNet/ScanNet#scannet-data

**Comment by luminous0809** [comment]
okok，thank you very much
