### ISSUE TITLE
effect is not good

### ISSUE THREAD

**Issue by zwl995** [GAP-LAB-CUHK-SZ/GaussReg#14]
Hello, I tried the data you provided, but it seems that the effect is not particularly good. For example, after A+B, some effects are less than A, as shown in the following figure.
![image](https://github.com/user-attachments/assets/680ea1ef-e117-4fc5-9e49-3bb8fe7f8f8c)
![image](https://github.com/user-attachments/assets/500b1ddc-5534-4c5e-9598-31ea55787537)

**Comment by Jiahao620** [comment]
You can refer to the answer [#11](https://github.com/GAP-LAB-CUHK-SZ/GaussReg/issues/11#issuecomment-2489925486). That is a better fusion strategy. Hope this helps you.

**Comment by zwl995** [comment]
Do you mean using gs_fusion.py? I ran it based on README, and I ran gs_fusion.py.

**Comment by Jiahao620** [comment]
Yes, I think the unsatisfactory performance is mainly due to the GS fusion strategy.
You can use the better strategy to modify the original gs_fusion.py.

**Comment by zwl995** [comment]
ok，thank you
