### ISSUE TITLE
Is it possible to directly provide train.pkl and test.pkl?

### ISSUE THREAD

**Issue by kokifhhh123** [GAP-LAB-CUHK-SZ/GaussReg#3]
Thank you for your work! 
A few months ago, I downloaded the Scannet-GSReg dataset, but I have since lost the train.pkl and test.pkl files. Since downloading the entire dataset takes a long time, I would like to ask if it would be possible to directly provide these two files? Thank you!

**Comment by Jiahao620** [comment]
All right, these two files are available in OneDrive: https://1drv.ms/f/c/31078419ab45666e/EvF8hMSxY1ZKpng7yYK-WzMB8RuFNZsx3OksoKYgqAVi7g?e=tBqma5
