### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by MT-Shark** [GAP-LAB-CUHK-SZ/GaussReg#6]
Thank you for providing the datasets! I download and unzip them successfully, everything is ok but I cannot find train.pkl & test.pkl these two files. I double checked and still could not find them ... Could you upload them separately to the onedrive? Thank you for your help!

**Comment by Jiahao620** [comment]
You can download train.pkl and test.pkl in OneDrive: https://1drv.ms/f/c/31078419ab45666e/EvF8hMSxY1ZKpng7yYK-WzMB8RuFNZsx3OksoKYgqAVi7g?e=tBqma5
