### ISSUE TITLE
About ScanNet-Reg dataset

### ISSUE THREAD

**Issue by Stefanlov1ez** [GAP-LAB-CUHK-SZ/GaussReg#9]
**Issue with Coarse Registration Training Procedure on GeoTransformer**

Hello,

We've encountered an issue while running the Coarse Registration training procedure for GeoTransformer. Specifically, executing the command

```python
python experiments/geotransformer.gaussian_splatting.indoor/trainval.py
```

results in an error. Here’s a screenshot of the error message for reference:
![Error Screenshot](https://github.com/user-attachments/assets/6e36171b-d57e-4f65-8268-d1149dd4f294).

Additionally, we noticed a discrepancy in the dataset structure. There are only 565 subdirectories within the `ScanNet-Reg` dataset directory, which may indicate an issue. Here’s a screenshot of the directory structure:
![Dataset Directory Structure](https://github.com/user-attachments/assets/aafc26de-a5a2-4d69-8422-7effdec0fb06).

To ensure that the dataset was correctly downloaded and merged, we checked that each compressed part file matches the expected size from the website: the first 92 files are each 3.9 GB, and the final part is 1.9 GB. After merging with the `copy` command and extracting, the resulting directory contained the observed 565 subdirectories.

Could you please advise on how to resolve this issue? Any insights into the dataset structure or configuration requirements would be greatly appreciated.

Thank you!

**Comment by Jiahao620** [comment]
Here’s a screenshot of my directory structure:
![image](https://github.com/user-attachments/assets/68bfcd30-6ad0-4077-8124-b1addc82df41)
The directory contains 1297 subdirectories and the total size of the dataset is 373G, which is roughly the same as the total size of the compressed package. Is it a decompression problem?

**Comment by Stefanlov1ez** [comment]
Yes, it was indeed a decompression issue. After re-extracting the files, the issue has been resolved. Now, there are 1,297 folders under the `train` directory and 82 folders under the `test` directory. Thank you for your help!
